### ISSUE TITLE
Get all B2SAFE Metadata

### ISSUE THREAD

**Issue by muccix** [EUDAT-B2STAGE/http-api#65]
It should be better to return all the B2SAFE Metadata.
The full list is the following:

```yaml
attribute: EUDAT/FIXED_CONTENT
value: False
units:

attribute: PID
value: 21.T12995/71b43d9e-49d5-11e7-8c95-040091643b25
units:

attribute: EUDAT/REPLICA
value: 21.T12996/72a98f60-49d5-11e7-ba6f-040091643baf,21.T12996/cfdffaa2-49d5-11e7-947c-040091643baf
units:

attribute: EUDAT/FIO
value: 21.T12995/71b43d9e-49d5-11e7-8c95-040091643b25
units:

attribute: EUDAT/ROR
value: 21.T12995/71b43d9e-49d5-11e7-8c95-040091643b25
units:

attribute: EUDAT/PARENT
value: 21.T12995/71b43d9e-49d5-11e7-8c95-040091643b25
units:

attribute: eudat_dpm_checksum_date:demoResc
value: 01496656675
units:
```
